
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SOFAS_PRODUCT_REQUEST = "SOFAS_PRODUCT_REQUEST";
export const SOFAS_PRODUCT_SUCCESS = "SOFAS_PRODUCT_SUCCESS";
export const SOFAS_PRODUCT_FAIL = "SOFAS_PRODUCT_FAIL";
export const CATEGORY_CLEAR_ERRORS = "SOFAS_CLEAR_ERRORS";


